#!/usr/bin/env python
# -*- coding: utf8 -*-
import urllib.request

req = urllib.request.Request("https://net.zju.edu.cn/cgi-bin/srun_portal",b"type=1&user_ip=&username=VPN_ID&local_auth=1&mac=&password=VPN_PASSWD&action=login&is_ldap=1&ac_id=3&wbaredirct=")
req.add_header("Content-Type", "application/x-www-form-urlencoded")
urllib.request.urlopen(req)
